### ISSUE TITLE
"Waiting for response..."

### ISSUE THREAD

**Issue by jjboy3232** [Krnl-staff/FAQ#40]
Whenever I try downloading the beta version of KNRL, it gets stuck on "Waiting for response..." Is this a known issue?

**Comment by oogaD** [comment]
Hello @jjboy3232. This issue is known but unfortunately, we don't have a specific page in the FAQ for this issue. The solution listed [here](https://github.com/Krnl-staff/FAQ/blob/main/Injection/Connection_Error_Retrying_Error.md#fix--using-zip) should help you.

If the solution above does not help you, then feel free to join our [Discord](https://krnl.place/invite) and ask around.
