### ISSUE TITLE
Roblox process not found [EXPLAINED, READ]

### ISSUE THREAD

**Issue by misterlobster7** [Krnl-staff/FAQ#51]
when i inject when opened roblox it says failed to find roblox process

**Comment by oogaD** [comment]
Hello @misterlobster7. If you or any other Krnl users reading this aren't in our [Discord server](https://krnl.place/invite), please make sure to **download [Discord](https://discord.com/download) and create a account to join our server if you wish to stay updated with Krnl news/announcements.**

*However*, regarding the `Roblox process not found` error(s), it seems to be caused by the full launch of the Byfron anti-cheat into Roblox. This seems to have affected all executors and all we ask is that you guys stay patient while the developers work hard towards unpatching Krnl 😄
